[zx-spectrum]
black =     0x000000
white =     0xFFFFFF
white_d =   0xCDCDCD
red =       0xFF0000
red_d =     0xCD0000
green =     0x00FF00
green_d =   0x00CD00
blue =      0x0000FF
blue_d =    0x0000CD
cyan =      0x00FFFF
cyan_d =    0x00CDCD
magenta =   0xFF00FF
magenta_d = 0xCD00CD
yellow =    0xFFFF00
yellow_d =  0xCDCD00

[gruvbox]
black =     0x282828
white =     0xEBDBB2
white_d =   0xA89984
red =       0xFB4934
red_d =     0xCC241D
green =     0xB8BB26
green_d =   0x98971A
blue =      0x83A598
blue_d =    0x458588
cyan =      0x8EC07C
cyan_d =    0x689D6A
magenta =   0xD3869B
magenta_d = 0xB16286
yellow =    0xFABD2F
yellow_d =  0xD79921

